### ISSUE TITLE
I tried a build on raspi/hyperiot which fails

### ISSUE THREAD

**Issue by githubgoucho** [marcelstoer/docker-nodemcu-build#10]
HypriotOS: root@black-pearl in /opt/nodemcu-firmware on master
$ docker run --rm -ti -v `pwd`:/opt/nodemcu-firmware marcelstoer/nodemcu-build
exec format error
docker: Error response from daemon: Cannot start container e87f1580bba3af57b5031d5882f09110a7f4396f2ac5f60f8a84ce37c0a44d1d: [9] System error: exec format error.

any sugestions?

**Comment by marcelstoer** [comment]
I can't support this due to lack of hardware (and time & interest atm), sorry. It's because the RaPi is ARM-based, see http://j.mp/24E6FUf for more.
