### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by signed-log** [marcelstoer/docker-nodemcu-build#102]
Seeing that there hasn't been an update to DNB since 2021, I'd like to ask if this project is still maintained. If it's not anymore, I'd love to take it over/help maintain it

**Comment by marcelstoer** [comment]
Thanks for reaching out. The project is still maintained as in "I'll fix bugs and accept PRs". However, the last version either just works or...nobody is using it anymore 😄 Hence, no new commits in quite a while.

The only thing that really bugs me about the current version is #101. So, I'd be gladly accepting your offer to help maintain this project.

**Comment by signed-log** [comment]
Would you be OK with having two distinct images for esp32 and esp8266. I am asking because of the [espressif/idf](https://hub.docker.com/r/espressif/idf) docker image which has everything ready to use

**Comment by marcelstoer** [comment]
Oh, interesting, didn't know they've been publishing IDF Docker images for years. Offering a single image certainly has its advantages for the user (maybe not for the maintainers).

- I wanted this image to use the same Ubuntu version as the one we use for the NodeMCU CI build on GitHub. That's currently not the case anymore; not good: https://github.com/nodemcu/nodemcu-firmware/blob/release/.github/workflows/build.yml#L23
- As NodeMCU for ESP32 pulls in the IDF as a Git submodule https://github.com/nodemcu/nodemcu-firmware/blob/dev-esp32/.gitmodules I see potential version conflicts it we were to use the IDF Docker image here.

**Comment by signed-log** [comment]
> I see potential version conflicts it we were to use the IDF Docker image here.

I would just find a way to bypass the submodule and use the built-in toolchain (this would mean just bypassing the Makefile and calling `idf.py` directly)

> I wanted this image to use the same Ubuntu version as we use for the NodeMCU CI build on GitHub. That's currently not the case anymore; not good

Understood, already made it use 20.04 in my local fork rn, will be able to test later

**Comment by marcelstoer** [comment]
> this would mean just bypassing the Makefile and calling `idf.py` directly

From what I understand this is quite likely to fail or be instable. NodeMCU is strictly tied to the one specific IDF version it references through the Git submodule.

**Comment by signed-log** [comment]
`v4.4.3` is a [tag](https://hub.docker.com/layers/espressif/idf/v4.4.3/images/sha256-8fc51413055e31684e1eac763b65cadfb202e90ef51a4d95768c21962398d63d?context=explore) for the Docker image

**Comment by marcelstoer** [comment]
We need to determine the correct IDF version based on the NodeMCU version the user checked out. It would be a major PITA if 

- we needed to release a new image every time the NodeMCU project bumps the IDF
- the user manually needed to pick the correct image tag/version every time they build their project

**Comment by signed-log** [comment]
Seeing the issue now, this is a non-starter yeah

**Comment by marcelstoer** [comment]
Any further discussions should continue at #101.
