### ISSUE TITLE
branch names with slashes result in build errors

### ISSUE THREAD

**Issue by simukka** [marcelstoer/docker-nodemcu-build#14]
Steps to reproduce:
1. Create a branch name along the lines of `build/foo` in nodemcu-firmware
2. Following the docker build instructions, start a build.
3. The build process will error out with `srec_cat: nodemcu_float_build/foo_20160601-2046.bin: 1: open: No such file or directory [2]: No such file or directory`

Exploratory fix:
`git rev-parse --abbrev-ref HEAD | sed -r 's/[\/\\]+/_/g'`

This will replace every occurrence of `/`, and `\` with `_`.

**Comment by marcelstoer** [comment]
Yep, that's to be expected. Your fix is fine. Can you please create a PR from your commit?

**Comment by marcelstoer** [comment]
Thanks.

**Comment by imediabank** [comment]
I Still have this error when build on (Fedora:VMbox:Windows10)

sed: -e expression #1, char 99: unknown option to `s'

Can you help ?
