### ISSUE TITLE
Docker container does not start, fail with below message

### ISSUE THREAD

**Issue by plkumar** [marcelstoer/docker-nodemcu-build#17]
Digest: sha256:c7926b18f6d6e22a2a31b4e60c2f5f055c2ca3c61d6530f29ef52bda787981a2
Status: Downloaded newer image for marcelstoer/nodemcu-build:latest
fatal: Not a git repository (or any parent up to mount point /opt/nodemcu-firmware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp: cannot stat 'tools/esp-open-sdk.tar.gz': No such file or directory

Docker Version:

Docker version 1.12.0-rc2, build 906eacd, experimental

**Comment by marcelstoer** [comment]
Looks like you cloned it to the wrong folder. See https://github.com/marcelstoer/docker-nodemcu-build#clone-the-nodemcu-firmware-repository
