### ISSUE TITLE
On windows cannot start nor from Kitematic nor from cmd

### ISSUE THREAD

**Issue by jjaskulowski** [marcelstoer/docker-nodemcu-build#18]
Install docker toolbox
Run "C:\Program Files\Git\bin\bash.exe" --login -i "C:\Program Files\Docker Toolbox\start.sh" aka "Docker Quickstart Terminal" shortcut

See:

```
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
```

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

Start interactive shell

Jaroslaw@lpatop MINGW64 ~
$

Run "C:\Program Files\Docker Toolbox\kitematic\Kitematic.exe" aka Kitematic (Alpha)

Search nodemcu-build by marcelstoer
Click Create...
After download, run.
See container logs:
fatal: Not a git repository (or any of the parent directories): .git
cp: cannot stat 'tools/esp-open-sdk.tar.gz': No such file or directory

Proceed according to https://hub.docker.com/r/marcelstoer/nodemcu-build/:

Open cmd:
Go to C:\Users\Jaroslaw (cmd already opens up in that dir)
Run git clone https://github.com/nodemcu/nodemcu-firmware.git
See, folder is there.
Go in to that folder.
Run:
docker run --rm -ti -v //c/Users/Jaroslaw/nodemcu-firmware:/opt/nodemcu-firmware marcelstoer/nodemcu-build

See output:
docker: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //./pipe/docker_engine: The system cannot find the file specified..
See 'docker run --help'.

There is a bug somewhere, either in documentation of in image.

PS. Thank you very much for this project.

**Comment by marcelstoer** [comment]
I don't know what it is but it's definitely an issue with Docker/Kitematic/installation and not with this image.
