### ISSUE TITLE
Consistent output image names

### ISSUE THREAD

**Issue by pjsg** [marcelstoer/docker-nodemcu-build#2]
It would be great if there was a link to the output image that was the same for each build (it can have the branch name). This would make the build/burn cycle easier as I don't need to change the input filename for the burner after each build. I was thinking that add a 'ln -f <name with time> <name without time>' would suffice.

**Comment by marcelstoer** [comment]
@alkorin was requesting something similar the other day.

He proposed to support passing the image name to the Docker command like so `docker run -e "IMAGE_NAME=foo" ...`. I'll implement that (and a few more improvements) in the next days.

**Comment by Alkorin** [comment]
:+1:

**Comment by pjsg** [comment]
Also, can you save the mapfile along with the image so that I can find the right mapfile when I get a crash (now that the node.bootreason() returns pointers!!)

**Comment by marcelstoer** [comment]
@pjsg not sure I understand. The `mapfile` is created in `app/`in your firmware directory. Maybe you were expecting it in `bin/` (like I did)?

**Comment by pjsg** [comment]
Yes -- the mapfile is created in app/ but then promptly overwritten by the next build. You don't ever get to see the float version of the mapfile as it is overwritten by the integer build. What I would like is to have the mapfile copied into the bin directory with a name just like the bin file (but ending with .map or similar)

**Comment by marcelstoer** [comment]
Ah, got it. Thanks for the clarification.

**Comment by marcelstoer** [comment]
Due to Docker's odd interpretation of what `latest` [means](http://container-solutions.com/docker-latest-confusion/) you need to run `docker pull marcelstoer/nodemcu-build` explicitly to work with the updated image if Docker downloaded it previously.
