### ISSUE TITLE
spiffsimg build doesn't appear to work

### ISSUE THREAD

**Issue by mikep01** [marcelstoer/docker-nodemcu-build#22]
Adding files to the ../local/fs directory doesn't seem to do anything, the file system remains empty.  Should the file section already be included in the bin output?

If I burn the bin files (00000,10000 individually the ESP goes into a loop with a bad file system.

Burning the file system bin to the indicated location seems to push the file system to a new address.

**Comment by marcelstoer** [comment]
> Adding files to the ../local/fs directory doesn't seem to do anything

I don't expect this to work because it's what #5 requests.

**Comment by mikep01** [comment]
Thanks for the reference!  I realized to late this is a build thing so nothing to do with this docker.
