### ISSUE TITLE
Trigonometric functions

### ISSUE THREAD

**Issue by KOT-KOCMOCMOHABT** [marcelstoer/docker-nodemcu-build#27]
How to enable Trigonometric functions in
https://github.com/nodemcu/nodemcu-firmware
before
docker run --rm -ti -v `pwd`:/opt/nodemcu-firmware marcelstoer/nodemcu-build ?
need math.sin(), math.cos(), math.tang() and more

**Comment by marcelstoer** [comment]
You can only configure what is there, see https://github.com/nodemcu/nodemcu-firmware/issues/1280. Next time pls consider https://github.com/marcelstoer/docker-nodemcu-build#support.
