### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by Axiom42** [marcelstoer/docker-nodemcu-build#3]
This link:

Follow the instructions at [https://docs.docker.com./installation](https://docs.docker.com/installation).

takes you to a 404 page. From reading information on the [docs](https://docs.docker.com/) page, it looks like they reorganized the documentation. Unfortunately it isn't clear from looking at the docs page where you should go to get the appropriate page.

**Comment by marcelstoer** [comment]
Thanks, I'll update the link. Just click the fat orange 'Get Started' button (top right) on the docs page.
