### ISSUE TITLE
cannot use event monitoring

### ISSUE THREAD

**Issue by technofection** [marcelstoer/docker-nodemcu-build#34]
I have successfully built the firmware and after build I got the following files in the bin directory
0x00000.bin
0x10000.bin
nodemcu_float_master_20180201-1623.bin
nodemcu_float_master_20180201-1623.map
nodemcu_integer_master_20180201-1623.bin
nodemcu_integer_master_20180201-1623.map

Then I have flashed "nodemcu_float_master_20180201-1623.bin" to the module and tried to write a small script which uses event monitoring, but I get the following error.

init.lua:20: attempt to index field 'eventmon' (a nil value)

When I built the firmware, I made sure that the following definition is uncommented.

#define WIFI_SDK_EVENT_MONITOR_ENABLE

Can someone tell me what wrong I must be doing?

I tried to use the couldbuild as well and I face the same issue..

Regards
Rakesh

**Comment by marcelstoer** [comment]
This issue list is [not a support forum](https://github.com/marcelstoer/docker-nodemcu-build#support).

For a user support issue one would have to see a minimal reproducible test case i.e. the code in `init.lua`. Note that `WIFI_SDK_EVENT_MONITOR_ENABLE` is for [`wifi.sta.config()`](https://nodemcu.readthedocs.io/en/master/en/modules/wifi/#wifistaconfig).
