### ISSUE TITLE
Update CN README to include latest changes

### ISSUE THREAD

**Issue by marcelstoer** [marcelstoer/docker-nodemcu-build#42]
See https://github.com/marcelstoer/docker-nodemcu-build/compare/master@%7B1day%7D...master#diff-04c6e90faac2675aa89e2176d2eec7d8

- NEW: support for building LFS
- NEW: no default command
- REMOVED: INTEGER_ONLY / FLOAT_ONLY parameters

@lou-lan if you find time for this in the next few weeks I would be very grateful

**Comment by lou-lan** [comment]
Please see PR #46 .

**Comment by marcelstoer** [comment]
Again, thank you so much!
