### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by loadedtech** [marcelstoer/docker-nodemcu-build#49]
Firstly, thanks for your great work ... 

I'm trying to do a build on OSX High Sierra using Docker Community Edition v18.06.1 and am getting the error when I try docker run --rm -ti -v 'pwd':/opt/nodemcu-firmware marcelstoer/nodemcu-build build:
fatal: Not a git repository (or any parent up to mount point /opt/nodemcu-firmware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

docker run --rm -ti -v 'pwd':/opt/nodemcu-firmware marcelstoer/nodemcu-build shows the "Welcome to the Docker image ... " message

I cloned the nodemcu-firmware repo (into my user folder), checked permissions, checked ownership, git status ... just can't figure it out. 

Does anyone have any clues, suggestions or things to check?

**Comment by loadedtech** [comment]
Ok, so I made progress by replacing 'pwd' with the full path to my nodemcu-firmware directory ... now all good.

I don't know why 'pwd' didn't work

**Comment by marcelstoer** [comment]
> I don't know why 'pwd' didn't work

Because you need to use back ticks rather than single quotes around `pwd`, look at https://github.com/marcelstoer/docker-nodemcu-build#run-this-image-with-docker-to-create-the-firmware carefully.

**Comment by loadedtech** [comment]
FYI the backticks threw a docker error:
opt/lua  marcelstoer/nodemcu-build lfs-im
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by HHHartmann** [comment]
Do you have a space in your path? 
In that case you would need to add double quotes around the pwd.
Like ''"`pwd`"'

**Comment by loadedtech** [comment]
yes, the path does have a space .. will try the double quotes

FYI, I posted a new issue / suggestion but for some reason it didn’t save / show up for me when I reloaded … did you get /see the issue?

Once again, thanks for your great work.

Hugh

**Comment by marcelstoer** [comment]
> for some reason it didn’t save / show up for me when I reloaded

Yeah, GitHub was instable the whole day https://status.github.com/messages
