### ISSUE TITLE
"Not a git repository" fatal error in WINDOWS 10

### ISSUE THREAD

**Issue by raffaelediana** [marcelstoer/docker-nodemcu-build#63]
Hello.

I downloaded master firmware and put it under my user directory and i assign all permissions also to Eveyone.

After i launched this command:
docker run --rm -it -v //c/Users/S227233/nodemcu-firmware-master:/opt/nodemcu-firmware marcelstoer/nodemcu-build build

But i had this:
fatal: Not a git repository (or any parent up to mount point /opt/nodemcu-firmware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

I also tryied this command:
docker run --rm -it -v //c/Users/S227233/nodemcu-firmware-master:/opt/nodemcu-firmware --env GIT_DISCOVERY_ACROSS_FILESYSTEM=1  marcelstoer/nodemcu-build build

But i had this othe one:
fatal: Not a git repository (or any of the parent directories): .git

I have problems also with LFS images:

docker run -it -v //c/Users/S227233/nodemcu-firmware-master:/opt/nodemcu-firmware -v //d/_PERSONALE/_NODE_MCU/_NUOVO_CODICE_CON_LFS --env GIT_DISCOVERY_ACROSS_FILESYSTEM=1  marcelstoer/nodemcu-build lfs-image
Error: No cross compiler found. You need to build the firmeware first.

Thanks in advance.

P.S.
Note: i use a company proxy...but i don't know if it is important because anyway docker works

**Comment by marcelstoer** [comment]
Again, GitHub issues are really a sub-par way to handle support requests. See https://github.com/marcelstoer/docker-nodemcu-build#support

In the Windows what do you see if you do

```
cd \Users\S227233\nodemcu-firmware-master
dir
```

**Comment by raffaelediana** [comment]
Sorry @marcelstoer i also wrote into StackOverflow with tag NODEMCU but really i'don't know if, here, is an issue for Windows or simply i did some wrong...

This is my nodemcu-firmware-master dir list:

01/15/2019  04:59 PM    <DIR>          .
01/15/2019  04:59 PM    <DIR>          ..
12/07/2018  10:47 PM               860 .gdbinit
12/07/2018  10:47 PM             4,200 .gdbinitlua
01/15/2019  03:56 PM    <DIR>          .github
12/07/2018  10:47 PM               175 .gitignore
12/07/2018  10:47 PM               228 .gitmodules
12/07/2018  10:47 PM               879 .travis.yml
01/15/2019  03:56 PM    <DIR>          app
01/15/2019  03:56 PM    <DIR>          bin
12/07/2018  10:47 PM             9,640 CONTRIBUTING.md
01/15/2019  03:56 PM    <DIR>          docs
01/15/2019  03:56 PM    <DIR>          ld
12/07/2018  10:47 PM             1,087 LICENSE
01/15/2019  03:09 PM    <DIR>          local
01/15/2019  03:56 PM    <DIR>          lua_examples
01/15/2019  03:09 PM    <DIR>          lua_modules
01/15/2019  04:39 PM            12,771 Makefile
12/07/2018  10:47 PM             3,803 mkdocs.yml
12/07/2018  10:47 PM             5,167 README.md
12/07/2018  10:47 PM               312 rtd-requirements.txt
01/15/2019  03:09 PM    <DIR>          sdk-overrides
01/15/2019  03:56 PM    <DIR>          tools

Thanks.
