### ISSUE TITLE
sed error on W10

### ISSUE THREAD

**Issue by bunlert274** [marcelstoer/docker-nodemcu-build#67]
i found error when use `docker run --rm -ti -v "{pwd}":/opt/nodefirmware docker-nodemcu-build build-esp32` error output `sed: -e expression #1, unknown option to `s'`

OS: Windows 10 Pro
Docker: Docker version 18.09.2, build 6247962

**Comment by marcelstoer** [comment]
Dup of #58

**Comment by bunlert274** [comment]
i fixed it from this issue not working and same error

**Comment by bunlert274** [comment]
wow, and i fixed this on build-esp32 in line 15-16, i add double quote to value this line
```
version_file="components/platform/include/user_version.h"
lua_header_file="components/lua/lua.h"

```
work for me!
