### ISSUE TITLE
How do I compile LUA scripts into the NodeMCU firmware?

### ISSUE THREAD

**Issue by GarMingLi** [marcelstoer/docker-nodemcu-build#71]
I compiled the nodemcu firmware in a Docker environment and burned it into modules.I wrote a LUA script using ESPlorer, and after debugging, I wanted to compile it into firmware.Just add the LUA script file to the "\nodemcu-firmware\local\fs" path. After recompiling, no new firmware will be generated and the compilation fails.The compilation information is as follows:
```
Segmentation fault
Makefile:74:recipe for target 'spiffsscript' failed
make[1]: *** [spiffsscript] Error 139
make[1]: Leaving directory '/opt/nodemcu-firmware/tools'
Makefile:348:recipe for target 'spiffs-image' failed
make: *** [spiffs-image] Error 2
```
Before I compiled, I enabled the configuration in the user_config.h file:
```
#define BUILD_SPIFFS
#define SPIFFS_FIXED_LOCATION        0x100000
#define SPIFFS_MAX_FILESYSTEM_SIZE    0x20000
#define SPIFFS_SIZE_1M_BOUNDARY
```
How can I compile LUA script files into the firmware?

**Comment by marcelstoer** [comment]
To create an LFS image see https://github.com/marcelstoer/docker-nodemcu-build#create-an-lfs-image-for-esp8266.
