### ISSUE TITLE
Worked fine for ESP8266 but failed for ESP32

### ISSUE THREAD

**Issue by stevemac00** [marcelstoer/docker-nodemcu-build#72]
I created a new docker volume then:
`docker run --rm -ti -v /volume1/docker/esp32/:/opt marcelstoer/nodemcu-build bash`
`cd /opt`
`git clone --recurse-submodules https://github.com/nodemcu/nodemcu-firmware.git`
`cd nodemcu-firmware`
`git checkout dev-esp32`
but it aborts with a listing of all the app/include/ files that will be overwritten.

**Comment by marcelstoer** [comment]
See https://github.com/marcelstoer/docker-nodemcu-build#support for user support -> closing

Just scanned this briefly but isn't your sequence of commands a bit odd? If you clone you get the `master` branch by default, then you checkout `dev-esp32`, then you should fetch all submodules of _that_ branch.
