### ISSUE TITLE
Support the new firmware info mechanism

### ISSUE THREAD

**Issue by marcelstoer** [marcelstoer/docker-nodemcu-build#73]
Build support for https://github.com/nodemcu/nodemcu-firmware/pull/2830 into `build-esp8266`.

Set the environment variable `USER_PROLOG`.

@HHHartmann do you think it's feasible/acceptable to just remove 70% of the stuff in `build-esp8266` and thereby no longer altering the welcome message for the frozen 1.5.x branch? It would be a relief to get rid of all that code 😉 

If I only commit this change after the firmware's upcoming master drop it wouldn't affect developers on the master branch.

**Comment by HHHartmann** [comment]
I would give it some time before removing the 70% thingy. Not everyone updates to the newest master all the time. Maybe one or two releases.

**Comment by marcelstoer** [comment]
Hhhmm, alright...then indeed I'll need to create this one big if-else probing for `NODE_VERSION_LONG` or `tools/update_buildinfo.sh` as discussed before.

**Comment by HHHartmann** [comment]
You could also rely on the`# define` trick for the time being. Setting USER_PROLOG won't hurt anybody.

**Comment by HHHartmann** [comment]
But then you would need another docker image update
