### ISSUE TITLE
requires libreadline-dev but not installed

### ISSUE THREAD

**Issue by stevemac00** [marcelstoer/docker-nodemcu-build#74]
I received this error on an esp32 build:
/opt/nodemcu-firmware/components/luac_cross/../lua/luaconf.h:305:31: fatal error: readline/readline.h: No such file or directory

for the next build, please apt-get install  -y **libreadline-dev** in the docker file

**Comment by marcelstoer** [comment]
It's actually there already: https://github.com/marcelstoer/docker-nodemcu-build/blob/20a27d422fbe9244571c336e3c9473982105dd33/Dockerfile#L19

You might have to do a `docker pull marcelstoer/docker-nodemcu-build` to update your local copy of the image as per https://github.com/marcelstoer/docker-nodemcu-build#bangbang-regular-updates
