### ISSUE TITLE
Maybe need update windows build command

### ISSUE THREAD

**Issue by hanfengcan** [marcelstoer/docker-nodemcu-build#75]
the section **Note for Windows users** said that use the command `docker run --rm -it -v //c/Users/<user>/<nodemcu-firmware>:/opt/nodemcu-firmware marcelstoer/nodemcu-build build`  to build the bin file.

but I found this command does work ok.

`docker run --rm -it -v f:/z.nodemcu/nodemcu-firmware:/opt/nodemcu-firmware marcelstoer/nodemcu-build build`

of course, my docker version is last

**Comment by marcelstoer** [comment]
Thanks for the feedback. It's quite possible that some Docker + Windows combinations support the simplified volume mount instructions. As don't use Windows myself I can't test.
