### ISSUE TITLE
could not do sethostname()

### ISSUE THREAD

**Issue by gatovelho** [marcelstoer/docker-nodemcu-build#9]
Hello,
first, Id like to thank you for sharing your time and skills with us.
Be warned, I am not a software-oriented fellow, so this may be my fault.
My problem:

wifi.sta.sethostname("myNodeMCU")

did not work on my (first) docker build (however  it does over the dev branch of freightanic).
NodeMCU returned some "call to nil" .

Could this be a configuration problem? (undefined some modules I had no interest on,
but kept the wifi module)

Best Regards
CS

**Comment by marcelstoer** [comment]
I don't do 1:1 support and this ain't an issue with this Docker image, see https://github.com/marcelstoer/docker-nodemcu-build#support.

> this may be my fault

It most likely is but we can't tell if you don't post code and the full error message.
