### ISSUE TITLE
ESP8266 build fails.

### ISSUE THREAD

**Issue by EFudd** [marcelstoer/docker-nodemcu-build#94]
Build for ESP8266:
win7 Docker - command line version

xxxx@ETW7P MINGW64 ~/nodemcu-firmware (release)
$ docker run --rm -ti -v `pwd`:/opt/nodemcu-firmware marcelstoer/nodemcu-build build
fatal: Not a git repository (or any parent up to mount point /opt/nodemcu-firmware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by marcelstoer** [comment]
https://github.com/marcelstoer/docker-nodemcu-build#note-for-windows-users
