### ISSUE TITLE
Updating nodeMCU firmware builds for SparkFun ESP32 Thing

### ISSUE THREAD

**Issue by Cyberfonic** [marcelstoer/docker-nodemcu-build#96]
The ESP32 Thing has a 26MHz xtal and thus the cloud built firmware doesn't work correctly.  The recommended solution is to build using [Docker based build environment](https://hub.docker.com/r/marcelstoer/nodemcu-build/). It worked fine for me back in April 2020.

I have the need to update the firmware so I followed the instructions on [NodeMCU firmware page](https://nodemcu.readthedocs.io/en/dev-esp32/build/) but I ended up making a hash of it.  Mainly because my git expertise is abysmal. I ended up wiping my old build directory and starting afresh.

Would have preferred to have some notes on how to accomplish a refresh of the firmware build directory.  Any chance that the above page could include some instructions to that effect?

**Comment by marcelstoer** [comment]
> the above page

Does this refer to the README of this project or the NodeMCU documentation?

**Comment by Cyberfonic** [comment]
I'm referring specifically to the instructions on:  https://hub.docker.com/r/marcelstoer/nodemcu-build/

They are good for first time use. But due to my lack of experience with git, I was unable to correctly update the files.

**Comment by marcelstoer** [comment]
I added a few notes with 34f99b0
